spring:
  application:
    name: review-service
  config:
    activate:
      on-profile: docker
server.port: 8080
server.error.include-message: always

logging:
  level:
    root: INFO
    mz.co.muianga: DEBUG
